site_name: Mon Labo de Test
site_url: https://lilevitchi.github.io/test-site/

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: fr
  palette:
    - scheme: slate
      primary: grey
      accent: deep orange
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top

extra_javascript:
  - javascripts/random_tips.js
  - javascripts/dynamic-sidebar-layout.js
  - javascripts/progress-bar.js
  
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
