site_name: Mon Labo de Test
site_url: https://lilevitchi.github.io/test-site/

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: fr
  palette:
    - scheme: slate
      primary: grey
      accent: deep orange
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top

extra_javascript:
  - javascripts/random_tips.js
  - javascripts/dynamic-sidebar-layout.js
  - javascripts/progress-bar.js
  
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Introduction: intro.md
  - Setup: setup.md
  - Mod Organizer 2: mo2.md
  - Utilities: utilities.md
  - Bug Fixes: bugfix.md
  - Base Finish: basefinish.md

  - User Interface: hud.md
  - Tweaks: tweaks.md
  - Gameplay: gameplay.md
  - Content: content.md
  - Visuals: visuals.md
  - Extended Finish: finish.md

  - Changelog: changelog.md
  - Resources: resources.md
  - FAQ: faq.md
  - Safe Modding: safe-modding.md
  - Wabbajack: wabbajack.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xxxx
    - icon: fontawesome/brands/github
      link: https://github.com/xxxx
    - icon: fontawesome/solid/heart
      link: https://ko-fi.com/xxxx
