site_name: Mon Labo de Test
site_url: https://lilevitchi.github.io/test-site/

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: fr
  palette:
    - scheme: slate
      primary: grey
      accent: deep orange
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.tracking

extra_javascript:
  - javascripts/random_tips.js
  - javascripts/dynamic-sidebar-layout.js
  - javascripts/progress-bar.js
  
extra_css:
  - stylesheets/base.css
  - stylesheets/layout.css
  - stylesheets/header.css
  - stylesheets/sidebar.css
  - stylesheets/components.css
  - stylesheets/hub.css
  - stylesheets/utilities.css
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Fallout 4:
      - Hub: fallout4/index.md
      - Guide Écrit: fallout4/intro.md
      - Guide Vidéo: https://youtu.be/m_CawhgGBGk
  - Fallout London:
      - Hub: fallout-london/index.md
      - Guide Écrit: fallout-london/intro.md
      - Guide Vidéo: "#"
  - Fallout New Vegas:
      - Hub: fnv/index.md
      - Guide Écrit: fnv/intro.md
      - Guide Vidéo: "#"
  - Tale of Two Wastelands:
      - Hub: ttw/index.md
      - Guide Écrit: ttw/intro.md
      - Guide Vidéo: "#"
  - Cyberpunk 2077:
      - Hub: cyberpunk/index.md
      - Guide Écrit: cyberpunk/intro.md
      - Guide Vidéo: "#"

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xxxx
    - icon: fontawesome/brands/github
      link: https://github.com/xxxx
    - icon: fontawesome/solid/heart
      link: https://ko-fi.com/xxxx
