site_name: Mon Labo de Test
site_url: https://lilevitchi.github.io/test-site/

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: fr
  palette:
    - scheme: slate
      primary: grey
      accent: deep orange
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top

extra_javascript:
  - javascripts/random_tips.js
  - javascripts/dynamic-sidebar-layout.js
  - javascripts/progress-bar.js
  - javascripts/hub-controller.js
  
extra_css:
  - 'css/base.css'        # Variables, resets, styles globaux
  - 'css/layout.css'      # Structure générale (md-container, md-main, content, footer)
  - 'css/header.css'      # Header fixe, progress bar
  - 'css/sidebar.css'     # Sidebars gauche/droite
  - 'css/components.css'  # Blocs spécifiques type bot, cards
  - 'css/hub.css'         # Hub full-screen, boutons, grid de jeux
  - 'css/utilities.css'   # Classes utilitaires, overrides, animations, curseurs
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Fallout 4:
      - Home: fallout4/index.md
      - Introduction: fallout4/intro.md
      - Setup: fallout4/setup.md
      - Bug Fixes: fallout4/bugfix.md
  - Fallout London: fallout-london/index.md
  - Fallout New Vegas: fnv/index.md
  - Tale of Two Wastelands: ttw/index.md
  - Cyberpunk 2077: cyberpunk/index.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xxxx
    - icon: fontawesome/brands/github
      link: https://github.com/xxxx
    - icon: fontawesome/solid/heart
      link: https://ko-fi.com/xxxx
