site_name: Mon Labo de Test
theme:
  name: material
  palette:
    # On force le mode sombre (Slate)
    - scheme: slate
      primary: grey
      accent: cyan
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top  # Ajoute un bouton "Retour en haut"
    - header.autohide # Masque la barre en haut quand on descend (tr√®s propre)

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
