site_name: Mon Labo de Test
site_url: https://lilevitchi.github.io/test-site/

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: fr
  palette:
    - scheme: slate
      primary: grey
      accent: deep orange
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top

extra_javascript:
  - javascripts/random_tips.js
  - javascripts/dynamic-sidebar-layout.js
  - javascripts/progress-bar.js
  
extra_css:
  - stylesheets/style.css
  - stylesheets/header.css
  - stylesheets/sidebar.css
  - stylesheets/hub2.css
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Fallout 4:
      - Home: fallout4/index.md
      - Introduction: fallout4/intro.md
      - Setup: fallout4/setup.md
      - Bug Fixes: fallout4/bugfix.md
  - Fallout London: fallout-london/index.md
  - Fallout New Vegas: fnv/index.md
  - Tale of Two Wastelands: ttw/index.md
  - Cyberpunk 2077: cyberpunk/index.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xxxx
    - icon: fontawesome/brands/github
      link: https://github.com/xxxx
    - icon: fontawesome/solid/heart
      link: https://ko-fi.com/xxxx
